apps/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("registo-particular/", views.signup_personal, name="signup-personal"),
    path("registo-empresarial/", views.signup_business, name="signup-business"),
    path("recuperacao-de-palavra-passe/", views.password_reset, name="password-reset"),
    path("alterar-palavra-passe/", views.password_change, name="password-change"),
    path("controller/", views.account_controller, name="controller"),
    # path('ver-perfil/', views.password_change, name="profile"),
    # path('editar-perfil/', views.password_change, name="password-change"),
]

apps/personal/urls.py
""" urls from personal """
from django.urls import path
from . import views

app_name= "personal"

urlpatterns = [
    path('perfil/atualizar/', views.profile_update, name="profile-update"),
    path('formacao/academica/nova/', views.add_academic_formation, name="add-academic-formation"),
    path('formacao/academica/eliminar/<uuid:id>', views.delete_academic_formation, name="delete-academic-formation"),
    path('formacao/profissional/nova/', views.add_profissional_formation, name="add-profissional-formation"),
    path('formacao/profissional/eliminar/<uuid:id>', views.delete_profissional_formation, name="delete-profissional-formation"),
    
    path('experiencia-profissional/nova/', views.add_profissional_experience, name="add-profissional-experience"),
    path('documentacao/atualizar/', views.add_documentation, name="add-documentation"),
    

    path('minha-carreira-profissional/', views.career, name="career"),

    path('vagas/', views.vacancy_list, name="vacancy-list"),
    path('vagas/<slug:company_slug>/detalhes/<uuid:vid>/', views.vacancy_detail, name="vacancy-detail"),
    path('candidaturas/adicionar-candidatura/<uuid:vid>/', views.apply_for_vacancy, name="apply-for-vacancy"),

    path('minhas-candidaturas/', views.my_candidates, name="my-candidates"),
    
    path('perfil-do-usuario/<uuid:uid>', views.user_profile, name="user-profile"),
]

setup/urls.py
""" Global url project """

from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pessoal/', include('apps.personal.urls')),
    path('empresarial/', include('apps.business.urls')),
    path('accounts/', include('apps.accounts.urls')),
    path('', include('apps.general.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/_alerts.html
{% load static %}
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <i class="bi bi-exclamation-circle-fill"></i>{{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}

{% endif %}

templates/partials/_color_config.html
<div class="theme-setting-wrapper">
    <div id="settings-trigger"><i class="typcn typcn-cog-outline"></i></div>
    <div id="theme-settings" class="settings-panel">
      <i class="settings-close typcn typcn-delete-outline"></i>
      <p class="settings-heading">SIDEBAR SKINS</p>
      <div class="sidebar-bg-options" id="sidebar-light-theme">
        <div class="img-ss rounded-circle bg-light border mr-3"></div>
        Light
      </div>
      <div class="sidebar-bg-options selected" id="sidebar-dark-theme">
        <div class="img-ss rounded-circle bg-dark border mr-3"></div>
        Dark
      </div>
      <p class="settings-heading mt-2">HEADER SKINS</p>
      <div class="color-tiles mx-0 px-4">
        <div class="tiles success"></div>
        <div class="tiles warning"></div>
        <div class="tiles danger"></div>
        <div class="tiles primary"></div>
        <div class="tiles info"></div>
        <div class="tiles dark"></div>
        <div class="tiles default border"></div>
      </div>
    </div>
  </div>

templates/partials/_footer.html
<footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
      <span class="text-center text-sm-left d-block d-sm-inline-block">Copyright © <a
          href="#" target="_blank">EJZ Tecnologia.com</a> 2024</span>
    </div>
  </footer>

templates/partials/_messages.html
{% load static %}
{% if messages %}
<div class="row" id="proBanner">
    <div class="col-12">
        <span class="d-flex align-items-center purchase-popup">
            {% for message in messages %}
            <p class="text-{{ message.tags }}">{{message}}</p>
            {% endfor %}
            <span class="btn download-button purchase-button ml-auto" style="visibility: hidden;">Invisible</span>
            <i class="typcn typcn-delete-outline text-primary" id="bannerClose"></i>
        </span>
    </div>
</div>
{% else %}
    <i class="typcn typcn-delete-outline text-primary d-none" id="bannerClose"></i>
{% endif %}

templates/partials/_navbar.html
{% load static %}
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
        <a class="navbar-brand brand-logo" href="{% url "accounts:controller" %}">
            <img src="{% static 'assets/images/logo/logo.png' %}"alt="logo" />
        </a>
        <a class="navbar-brand brand-logo-mini" href="{% url "accounts:controller" %}">
            <img src="{% static 'assets/images/logo/logo.png' %}" alt="logo" />
        </a>
        <button class="navbar-toggler navbar-toggler align-self-center d-none d-lg-flex" type="button" data-toggle="minimize">
            <span class="bi bi-list"></span>
        </button>
    </div>

    <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
        <!-- <ul class="navbar-nav mr-lg-2">
            <li class="nav-item  d-none d-lg-flex">
                <a class="nav-link" href="#">
                    Calendar
                </a>
            </li>
            
            <li class="nav-item  d-none d-lg-flex">
                <a class="nav-link active" href="#">
                    Statistic
                </a>
            </li>

            <li class="nav-item  d-none d-lg-flex">
                <a class="nav-link" href="#">
                    Employee
                </a>
            </li>
        </ul> -->


        <ul class="navbar-nav navbar-nav-right">
            {% comment %} <li class="nav-item dropdown  d-flex">
                <a class="nav-link count-indicator dropdown-toggle d-flex align-items-center justify-content-center"
                    id="notificationDropdown" href="#" data-toggle="dropdown">
                    <i class="bi bi-bell-fill mr-0"></i>
                    <span class="count bg-danger">9</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list"
                    aria-labelledby="notificationDropdown">
                    <p class="mb-0 font-weight-normal float-left dropdown-header">Notifications</p>
                    
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-info">
                                <i class="bi bi-person-fill mx-0"></i>
                            </div>
                        </div>
                        <div class="preview-item-content">
                            <h6 class="preview-subject font-weight-normal">Novo registro user registration</h6>
                            <p class="font-weight-light small-text mb-0">
                                2 days ago
                            </p>
                        </div>
                    </a>
                </div>
            </li> {% endcomment %}

            <li class="nav-item nav-profile dropdown">
                <a class="nav-link dropdown-toggle  pl-0 pr-0" href="#" data-toggle="dropdown" id="profileDropdown">
                    <i class="bi bi-person-fill mr-0"></i>
                    <span class="nav-profile-name">{{ request.user.get_full_name }}</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
                    {% if request.user.type == 'P' %}
                    <a class="dropdown-item" href="{% url "personal:career" %}">
                        <i class="bi bi-gear text-primary"></i>
                        Edição de Perfil
                    </a>
                    {% endif %}
                    <form method="post" action="{% url 'accounts:logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="dropdown-item">
                            <i class="bi bi-power text-primary"></i>
                            Logout
                        </button>
                    </form>
                </div>
            </li>
        </ul>

        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="bi bi-list"></span>
        </button>
    </div>
</nav>