apps/business/urls.py
""" Business urls for """
from django.urls import path
from . import views

app_name = "business"

urlpatterns = [
    path('vagas/', views.vacancy_list, name="vacancy-list"),
    path('vagas/nova-vaga/', views.register_vacancy, name="register-vacancy"),
    path('vagas/apagar-vaga/<uuid:vid>/', views.delete_vacancy, name="delete-vacancy"),
    path('vagas/adicionar-requisito/<uuid:vid>/', views.add_vacancy_skills, name="add-vacancy-skill"),
    path('vagas/adicionar-responsabilidade/<uuid:vid>/', views.add_vacancy_responsibilities, name="add-vacancy-responsibility"),
    path('vagas/adicionar-beneficio/<uuid:vid>/', views.add_vacancy_benefits, name="add-vacancy-benefits"),
    path('vagas/edit-vaga/<uuid:vid>/', views.edit_vacancy, name="edit-vacancy"),
    path('vagas/<slug:company_slug>/detalhes/<uuid:vid>/', views.vacancy_detail, name="vacancy-detail"),
    
    path('vagas/requisito/apagar/<uuid:sid>/', views.delete_skill, name="delete-skill"),
    path('vagas/beneficio/apagar/<uuid:bid>/', views.delete_benefit, name="delete-benefit"),
    path('vagas/responsabilidade/apagar/<uuid:rid>/', views.delete_responsibility, name="delete-responsibility"),
    
    path('perfil-do-usuario/<uuid:uid>/', views.user_profile, name="user-profile"),
    path('perfil-do-usuario/candidato/<uuid:uid>/', views.candidate_user_profile, name="candidate-user-profile"),
    path('candidaturas/<uuid:vid>/', views.candidacy_list, name="candidacy-list"),
    path('candidaturas/analise/<uuid:vid>/', views.candidacy_analyses, name="candidacy-analyses"),
]

apps/personal/urls.py
""" urls from personal """
from django.urls import path
from . import views

app_name= "personal"

urlpatterns = [
    path('perfil/atualizar/', views.profile_update, name="profile-update"),
    path('formacao/academica/nova/', views.add_academic_formation, name="add-academic-formation"),
    path('formacao/academica/eliminar/<uuid:id>', views.delete_academic_formation, name="delete-academic-formation"),
    path('formacao/profissional/nova/', views.add_profissional_formation, name="add-profissional-formation"),
    path('formacao/profissional/eliminar/<uuid:id>', views.delete_profissional_formation, name="delete-profissional-formation"),
    
    path('experiencia-profissional/nova/', views.add_profissional_experience, name="add-profissional-experience"),
    path('documentacao/atualizar/', views.add_documentation, name="add-documentation"),
    

    path('minha-carreira-profissional/', views.career, name="career"),

    path('vagas/', views.vacancy_list, name="vacancy-list"),
    path('vagas/<slug:company_slug>/detalhes/<uuid:vid>/', views.vacancy_detail, name="vacancy-detail"),
    path('candidaturas/adicionar-candidatura/<uuid:vid>/', views.apply_for_vacancy, name="apply-for-vacancy"),

    path('minhas-candidaturas/', views.my_candidates, name="my-candidates"),
    
    path('perfil-do-usuario/<uuid:uid>', views.user_profile, name="user-profile"),
]

setup/urls.py
""" Global url project """

from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pessoal/', include('apps.personal.urls')),
    path('empresarial/', include('apps.business.urls')),
    path('accounts/', include('apps.accounts.urls')),
    path('', include('apps.general.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/business/forms/vacancy_benefits_form.py
"""register form for vacancy skills"""

from django import forms
from ..models import Benefit


class VacancyBenefitForm(forms.ModelForm):
    """register vacancy benefit form model"""
    class Meta:
        model = Benefit
        fields = ['title']

    title = forms.CharField(
        label="Curta Descrição",
        required=True,
        max_length=255,
        widget=forms.TextInput(attrs={
            "placeholder":"Descrição",
            "class":"form-control",
            "tamanho":"col-12 mt-4",
        }),
        error_messages={
            "required":"O campo Descrição não pode estar vazio!" 
        },
    )

    def clean_title(self):
        """remove the whitespaces at the end of string"""
        return self.cleaned_data.get('title').strip()

apps/business/forms/vacancy_responsibilities_form.py
"""register form for vacancy skills"""

from django import forms
from ..models import Responsibility


class VacancyResponsibilityForm(forms.ModelForm):
    """register vacancy form model"""
    class Meta:
        model = Responsibility
        fields = ['title']

    title = forms.CharField(
        label="Curta Descrição",
        required=True,
        max_length=255,
        widget=forms.TextInput(attrs={
            "placeholder":"Descrição",
            "class":"form-control",
            "tamanho":"col-12 mt-4",
        }),
        error_messages={
            "required":"O campo Descrição não pode estar vazio!" 
        },
    )

    def clean_title(self):
        """remove the whitespaces at the end of string"""
        return self.cleaned_data.get('title').strip()

apps/business/forms/vacancy_skills_form.py
"""register form for vacancy skills"""

from django import forms
from ..models import Skill


class VacancySkillForm(forms.ModelForm):
    """register vacancy form model"""
    class Meta:
        model = Skill
        fields = ['title']

    title = forms.CharField(
        label="Curta Descrição",
        required=True,
        max_length=255,
        widget=forms.TextInput(attrs={
            "placeholder":"Descrição",
            "class":"form-control",
            "tamanho":"col-12 mt-4",
        }),
        error_messages={
            "required":"O campo Descrição não pode estar vazio!" 
        },
    )

    def clean_title(self):
        """remove the whitespaces at the end of string"""
        return self.cleaned_data.get('title').strip()

apps/business/views.py
""" Business Views"""
from django.db.models import Count
from django.views import View
from django.urls import reverse
from django.views import generic
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.contrib.auth import get_user_model

from apps.personal.models import Formation, ProfissionalExperience, Documentation
from apps.personal.models import AcademicFormationItem, ProfissionalFormationItem
from apps.personal.models import ProfissionalExperienceItem

from apps.business.models import Skill, Responsibility, Benefit
from .models import Vacancy, Candidate
from .forms import RegisterVacancyForm, VacancySkillForm
from .forms import VacancyResponsibilityForm, VacancyBenefitForm
from . import charts
User = get_user_model()


class CandidateUserProfileView(View):
    template_name = "business/candidate-user-profile.html"
    def get(self, request, *args, **kwargs):
        owner = User.objects.get(uid=self.kwargs.get('uid'))
        formation, _ = Formation.objects.get_or_create(user=owner)
        experience, _ = ProfissionalExperience.objects.get_or_create(user=owner)
        documentation, _ = Documentation.objects.get_or_create(user=owner)

        acad_formation_items = AcademicFormationItem.objects.filter(formation=formation)
        prof_formation_items = ProfissionalFormationItem.objects.filter(formation=formation)
        prof_experience_items = ProfissionalExperienceItem.objects.filter(profissional_experience=experience)

        candidates = Candidate.objects.filter(user=owner)
        

        return render(self.request, self.template_name, {
            "acad_formation_items":acad_formation_items,
            "prof_formation_items":prof_formation_items,
            "prof_experience_items":prof_experience_items,
            "documentation": documentation,
            "candidates":candidates,
            "owner":owner,
        })
candidate_user_profile = CandidateUserProfileView.as_view()

def user_profile(request, uid):
    total_vacancies = Vacancy.objects.filter(company=request.user)
    total_vacancies_active = Vacancy.objects.filter(company=request.user, expiration_data__gt = timezone.now().date())
    total_users = User.objects.exclude(uid=request.user.uid)
    total_candidates = Candidate.objects.all()
    labels_bar_vacancies_by_month, data_bar_vacancies_by_month = charts.get_vacancies_by_month()
    labels_users_by_month_line, data_users_by_month_line = charts.get_users_by_month()
    labels_users_gender_pie, data_users_gender_pie = charts.get_users_gender_pie()
    labels_users_without_pie, data_users_without_pie = charts.get_users_without_cv_pie()

    print(labels_users_by_month_line)
    print(data_users_by_month_line)

    return render(request, "business/user-profile.html", {
        'total_vacancies': total_vacancies,
        'total_vacancies_active': total_vacancies_active,
        'total_users': total_users,
        'total_candidates': total_candidates,
        'labels_bar_vacancies_by_month':labels_bar_vacancies_by_month,
        'data_bar_vacancies_by_month':data_bar_vacancies_by_month,
        'labels_users_by_month_line':labels_users_by_month_line,
        'data_users_by_month_line':data_users_by_month_line,
        'labels_users_gender_pie':labels_users_gender_pie,
        'data_users_gender_pie':data_users_gender_pie,
        'labels_users_without_pie':labels_users_without_pie,
        'data_users_without_pie':data_users_without_pie,
    })

@method_decorator(
    [login_required(login_url='landing_page', redirect_field_name="next")],name='dispatch')
class CandidacyAnalysesView(View):
    """analyses View """
    model = Candidate
    template_name = "business/candidacy_analyses.html"
    context_object_name = 'candidates'
    def get(self, request, *args, **kwargs):
        """get all  candidates applied to the vacancy"""
        vacancy = Vacancy.objects.get(vid=self.kwargs.get('vid'))
        candidates = Candidate.objects.filter(vacancy=vacancy)
        total_candidates = len(candidates)
        # paginator = Paginator(list_candidates,5)
        # candidates = paginator.get_page(self.request.GET.get('page'))

        return render(self.request, self.template_name,
                      {'candidates': candidates, "vacancy": vacancy,
                       "total_candidates":total_candidates})
candidacy_analyses = CandidacyAnalysesView.as_view()


@method_decorator(
    [login_required(login_url='landing_page', redirect_field_name="next")],name='dispatch')
class CandidacyListView(View):
    """List View for all candidate applied in a vacancy"""
    model = Candidate
    template_name = "business/candidacy_list.html"
    context_object_name = 'candidates'
    paginate_by = 5
    def get(self, request, *args, **kwargs):
        """get all  candidates applied to the vacancy"""
        vacancy = Vacancy.objects.get(vid=self.kwargs.get('vid'))
        list_candidates = Candidate.objects.filter(vacancy=vacancy)
        total_candidates = len(list_candidates)
        paginator = Paginator(list_candidates,5)
        candidates = paginator.get_page(self.request.GET.get('page'))

        return render(self.request, self.template_name, {'candidates': candidates, "vacancy": vacancy, "total_candidates":total_candidates})
candidacy_list = CandidacyListView.as_view()

class _BasicVacancyEditViewModel(View):
    template_name = "business/vacancy_edit.html"
    form_class = RegisterVacancyForm

    def get_instance(self) -> Vacancy:
        """get the current edit instance of vacancy 
        Returns:
            Vacancy: current vacancy
        """
        vacancy = Vacancy.objects.get(vid=self.kwargs.get("vid"))
        return vacancy

    def get(self, *args, **kwargs):
        """retrieve edit page with forms"""
        vacancy = self.get_instance()
        vacancy_information_form = self.form_class(self.request.session.get("vacancy_basic_form_data", None),instance=vacancy)
        vacancy_skills_form = VacancySkillForm(self.request.session.get("vacancy_skills_form_data", None))
        vacancy_responsibilities_form = VacancySkillForm(self.request.session.get("vacancy_responsibility_form_data", None))
        vacancy_benefits_form = VacancySkillForm(self.request.session.get("vacancy_benefits_form_data", None))
        return render(self.request, self.template_name, {
            "vacancy":vacancy, 
            "vacancy_information_form":vacancy_information_form,
            "vacancy_skills_form":vacancy_skills_form,
            "vacancy_responsibilities_form":vacancy_responsibilities_form,
            "vacancy_benefits_form":vacancy_benefits_form
        })

@method_decorator(
    [login_required(login_url='landing_page', redirect_field_name="next")],name='dispatch')
class VacancyBenefitsViewEdit(_BasicVacancyEditViewModel):
    """edit vacancy skills view"""
    form_class = VacancyBenefitForm

    def post(self,*args, **kwargs):
        """ save benefits"""
        self.request.session['vacancy_benefits_form_data'] = self.request.POST
        form = self.form_class(self.request.POST)
        if form.is_valid():
            benefit = form.save(commit=False)
            benefit.vacancy = self.get_instance()
            benefit.save()
            messages.success(self.request, "Benefício salvo com sucesso!")
            del self.request.session['vacancy_benefits_form_data']
        print(form.errors)
        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER') or '')
add_vacancy_benefits = VacancyBenefitsViewEdit.as_view()

@method_decorator(
    [login_required(login_url='landing_page', redirect_field_name="next")],name='dispatch')
class VacancyResponsibilityViewEdit(_BasicVacancyEditViewModel):
    """edit vacancy responsibility view"""
    form_class = VacancyResponsibilityForm

    def post(self,*args, **kwargs):
        """ save responsibility"""
        self.request.session['vacancy_responsibility_form_data'] = self.request.POST
        form = self.form_class(self.request.POST)
        if form.is_valid():
            responsibility = form.save(commit=False)
            responsibility.vacancy = self.get_instance()
            responsibility.save()
            messages.success(self.request, "Responsabilidade salva com sucesso!")
            del self.request.session['vacancy_responsibility_form_data']
        print(form.errors)
        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER') or '')
add_vacancy_responsibilities = VacancyResponsibilityViewEdit.as_view()

@method_decorator(
    [login_required(login_url='landing_page', redirect_field_name="next")],name='dispatch')
class VacancySkillSViewEdit(_BasicVacancyEditViewModel):
    """edit vacancy skills view"""
    form_class = VacancySkillForm

    def post(self,*args, **kwargs):
        """ save skills"""
        self.request.session['vacancy_skills_form_data'] = self.request.POST
        form = self.form_class(self.request.POST)
        if form.is_valid():
            skill = form.save(commit=False)
            skill.vacancy = self.get_instance()
            skill.save()
            messages.success(self.request, "Requisito salvo com sucesso!")
            del self.request.session['vacancy_skills_form_data']
        print(form.errors)
        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER') or '')
add_vacancy_skills = VacancySkillSViewEdit.as_view()

@method_decorator(
    [login_required(login_url='landing_page', redirect_field_name="next")],name='dispatch')
class DeleteResponsibilityView(View):
    """delete vacancy responsibility view"""
    def post(self, *args, **kwargs):
        """post method for delete processing request
        Returns:
            http redirect response: redirect url view
        """

templates/business/register_vacancy.html
{% extends 'business/base.html' %}
{% load static %}

{% block metas %}
  <meta name="description" content="Encontre os melhores talentos para sua organização" />
  <meta name="keywords" content="Talentos, Trabalhador, Recurso, Contratação, Valor" />
{% endblock %}

{% block title %}
  Nova Vaga
{% endblock %}

{% block local_style %}

{% endblock %}

{% block content %}
  <div class="content-wrapper">
    <div class="d-flex justify-content-end">
      {% include 'partials/_messages.html' %}
    </div>

    {% comment %} <section>
      <h2>Vagas Candidaturas</h2>
      <div class="row justify-content-center">
        <div class="col-12 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h2>Formação Acadêmica</h2>
              <p class="card-description">Os seus dados ajudaram os recrutadores a saber mais sobre você!</p>

              <form method="post" action="{% url 'personal:add-academic-formation' %}" class="forms-sample">
                {% csrf_token %}

                <div class="form-group">
                  {% include 'partials/_alerts.html' %}
                </div>

                <div class="row justify-content-end text-start">
                  {% for field in personal_academic_formation_form.visible_fields %}
                    <div class="col-12 col-sm-6 col-md-6 col-lg-4">
                      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                      {{ field }}

                      {% if field.help_text %}
                        <p class="text-muted">
                          <small>{{ field.help_text }}</small>
                        </p>
                      {% endif %}

                      {% if field.errors %}
                        <div class="text-danger error-messages">{{ field.errors }}</div>
                      {% endif %}
                    </div>
                  {% endfor %}

                  <div class="col-12 col-sm-6 col-md-6 col-lg-4">
                    <label for="" class="w-100" style="visibility: hidden;">Adicionar</label>
                    <button type="submit" class="btn btn-primary w-100" id="btnAddItens">
                      <i class="bi bi-plus"></i>
                      Adicionar
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section> {% endcomment %}

    <section>
      <div class="row justify-content-center">
        <div class="col-12 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h2 class="card-title">Detalhes da Vaga</h2>
              <div class="border"></div>
              <p class="card-description mt-3">Uma vaga bem detalhada tem mais chances de despertar o interesse dos candidatos certos</p>
              <form method="post" action="{% url 'business:register-vacancy' %}" class="forms-sample">
                {% csrf_token %}

                <div class="row justify-content-end text-start">
                  {% for field in register_vacancy_form.visible_fields %}
                    <div class="{{ field.field.widget.attrs.tamanho }}">
                      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                      {{ field }}

                      {% if field.help_text %}
                        <p class="text-muted">
                          <small>{{ field.help_text }}</small>
                        </p>
                      {% endif %}

                      {% if field.errors %}
                        <div class="text-danger error-messages">{{ field.errors }}</div>
                      {% endif %}
                    </div>
                  {% endfor %}

                  <div class="col-12 col-sm-6 col-md-6 col-lg-4">
                    <label for="" class="w-100" style="visibility: hidden;">Salvar</label>
                    <button type="submit" class="btn btn-primary w-100" id="btnAddItens">
                      <i class="bi bi-save"></i>
                      Salvar
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
{% endblock %}

{% block local_script %}

{% endblock %}

templates/business/vacancy_edit.html
{% extends 'business/base.html' %}
{% load static %}

{% block metas %}
  <meta name="description" content="Edição de Vaga" />
  <meta name="keywords" content="Vagas, Editar, Edição" />
{% endblock %}

{% block title %}
  Edição de Vaga
{% endblock %}

{% block local_style %}

{% endblock %}

{% block content %}
  <main class="content-wrapper">
    <div class="d-flex justify-content-end">
      {% include 'partials/_messages.html' %}
    </div>

    <section>
      <div class="row">
        <div class="col-12 col-lg-8 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between">
                    <a href="{{ vacancy.get_absolute_url }}" class="btn btn-primary">
                        <i class="bi bi-arrow-left"></i>
                        Ver Vaga
                    </a>
                    <h2 class="card-title">
                        Vaga: <span class="text-primary">{{ vacancy.title }}</span>
                    </h2>
                </div>

              <ul class="nav nav-pills mb-3 mt-4" id="pills-tab" role="tablist">
                <li class="nav-item" role="presentation">
                  <button class="nav-link " id="pills-basic-informations-tab" data-toggle="pill" data-target="#pills-basic-informations" type="button" role="tab" aria-controls="pills-basic-informations" aria-selected="true">
                    <i class="bi bi-person-vcard"></i> Informações Gerais</button>
                  </button>
                </li>

                <li class="nav-item" role="presentation">
                  <button class="nav-link active" id="pills-skills-tab" data-toggle="pill" data-target="#pills-skills" type="button" role="tab" aria-controls="pills-skills" aria-selected="false">
                    <i class="bi bi-journals"></i>
                    Requisitos Técnicos
                  </button>
                </li>
                
                <li class="nav-item" role="presentation">
                  <button class="nav-link" id="pills-responsibilities-tab" data-toggle="pill" data-target="#pills-responsibilities" type="button" role="tab" aria-controls="pills-responsibilities" aria-selected="false">
                    <i class="bi bi-person-lines-fill"></i>
                    Resposabilidades
                  </button>
                </li>
                
                <li class="nav-item" role="presentation">
                  <button class="nav-link" id="pills-benefits-tab" data-toggle="pill" data-target="#pills-benefits" type="button" role="tab" aria-controls="pills-benefits" aria-selected="false">
                    <i class="bi bi-file-earmark-text"></i>
                    Beneficios
                  </button>
                </li>
              </ul>
              <div class="tab-content" id="pills-tabContent">
                {% include "business/partials/_vacancy_information_tab.html" %}
                {% include "business/partials/_vacancy_requirements_tab.html" %}
                {% include "business/partials/_vacancy_responsabilities_tab.html" %}
                {% include "business/partials/_vacancy_benefits_tab.html" %}
              </div>
              
            </div>

            <div class="d-sm-flex justify-content-end m-3">
              <div>
                <button type="button" class="btn btn-sm btn-danger mr-2" data-toggle="modal" data-target="#exampleModal">
                  <i class="bi bi-trash"></i>
                  Apagar Anúncio de Vaga
                </button>
              </div>
            </div>
          </div>
        </div>

        <div class="col-12 col-lg-4 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                  <h2 class="card-title">
                    Vaga: <span class="text-primary">{{ vacancy.title }}</span>
                </h2>
                  <p class="h5">
                    <div class="d-flex">
                        <i class="bi bi-clock-fill"></i> 
                        Data de registro: 
                    </div>
                    <p class="mt-2">
                        <span class=" p-1 alert-danger">{{ vacancy.created_at }}</span>
                    </p>
                  </p>
              
                  <p class="card-title" style="font-size:medium;">
                    <span>
                      <i class="bi bi-geo-alt-fill"></i>
                      <span class="badge badge-warning">{{ vacancy.city }}</span>
                    </span>
              
                    <span class="mx-3">
                      <i class="bi bi-briefcase-fill"></i>
                      <span class="badge badge-success">{{ vacancy.job_type }}</span>
                    </span>
                  </p>
              
                  <div>
                    <p>{{ vacancy.description|safe }}</p>
                  </div>
              
                  {% if vacancy.get_skills %}
                    <div class="mt-5">
                      <h2 class="h4">Requisitos Técnicos</h2>
                      <ul class="ml-4">
                        {% for skill in vacancy.get_skills %}
                          <li>
                            <div class="d-flex">
                                {{ skill.title }}
                                -
                                <form action='{% url "business:delete-skill" skill.sid %}' method="post">
                                    {% csrf_token %}
                                    <button type="submit" class='btn '>
                                        <i class="bi bi-trash text-danger"></i>
                                    </button>
                                </form> 
                            </div>
                          </li>
                        {% empty %}
                          <p class="text-muted">Não há requisitos especificados para esta vaga</p>
                        {% endfor %}
                      </ul>
                    </div>
                  {% endif %}
              
                  {% if vacancy.get_responsibilities %}
                    <div class="mt-5">
                      <h2 class="h4">Responsabilidades</h2>
                      <ul class="ml-4">
                        {% for responsibility in vacancy.get_responsibilities %}
                        <li>
                            <div class="d-flex">
                            {{ responsibility.title }}
                            - <form action='{% url "business:delete-responsibility" responsibility.rid %}' method="post">
                                {% csrf_token %}
                                <button type="submit" class='btn '>
                                    <i class="bi bi-trash text-danger"></i>
                                </button>
                            </form> 
                        </div>
                          </li>
                        {% empty %}
                          <p class="text-muted">Não há responsabilidades especificadas para esta vaga</p>
                        {% endfor %}
                      </ul>
                    </div>
                  {% endif %}
              
                  {% if vacancy.get_benefits %}
                    <div class="mt-5">
                      <h2 class="h4">Benefícios</h2>
                      <ul class="ml-4">
                        {% for benefit in vacancy.get_benefits %}
                          <li>
                            <div class="d-flex">
                            {{ benefit.title }}
                            - <form action='{% url "business:delete-benefit" benefit.bid %}' method="post">
                                {% csrf_token %}
                                <button type="submit" class='btn '>
                                    <i class="bi bi-trash text-danger"></i>
                                </button>
                            </form> 
                        </div>
                          </li>
                        {% empty %}
                          <p class="text-muted">Não há responsabilidades especificadas para esta vaga</p>
                        {% endfor %}
                      </ul>
                    </div>
                  {% endif %}
                </div>
              </div>
        </div>
      </div>
    </section>

    {% include 'business/partials/_vacancy_delete_modal.html' %}
  </main>
{% endblock %}

{% block local_script %}
<script src="{% static 'assets/js/file-upload.js' %}"></script>
  <script src="{% static 'assets/js/typeahead.js' %}"></script>
  <script src="{% static 'assets/js/select2.js' %}"></script>
{% endblock %}

templates/business/vacancy_list.html
{% extends 'business/base.html' %}
{% load static %}

{% block metas %}
  <meta name="description" content="Encontre os melhores talentos para sua organização" />
  <meta name="keywords" content="Talentos, Trabalhador, Recurso, Contratação, Valor" />
{% endblock %}

{% block title %}
  Vagas
{% endblock %}

{% block local_style %}
{% endblock %}

{% block content %}
  <div class="content-wrapper">
    <div class="d-flex justify-content-end">
      {% include 'partials/_messages.html' %}
    </div>

    <div class="jumbotron bg-white">
      <h1 class="display-4">Vagas e Candidaturas</h1>
      <p class="lead">Contrate pessoas com habilidades, mas também com valores alinhados à cultura da empresa</p>
      <hr class="my-4" />
      <p>Grandes profissionais aguardam por grandes companhias lá fora. Está pronto para recebe-los?</p>
      <a href="{% url 'business:register-vacancy' %}" class="btn btn-primary">
        <i class="bi bi-plus-circle-fill"></i>
        Nova Vaga
      </a>
    </div>

    <section>
      <h2>Vagas Candidaturas</h2>
    </section>

    <div class="row">
      {% for vacancy in vacancies %}
        <article class="col-12 col-sm-6 col-xl-4 my-2">
          <div class="card rounded-lg" style="min-width: 20rem; min-height: 520px;">
            <img src="{{ vacancy.image_url }}" class="vacancy-image card-img-top" alt="{{ vacancy.title }}" style="width:100%; max-height:230px;" />
            
            <div class="card-body border-top">
                <a href="{{ vacancy.get_absolute_url }}"><h5 class="card-title vacancy-title text-center text-primary">{{ vacancy.title }}</h5></a>
              <div class="d-flex justify-content-between ">
                <span class="card-title text-muted">
                    <i class="bi bi-geo-alt-fill"></i>
                    {{vacancy.city}}
                </span>
                <span class="card-title p-2 alert-success">{{ vacancy.job_type }}</span>
              </div>
              <p class="card-text align-self-end" style="min-height: 90px;">{{ vacancy.description|slice:":135" }}...</p>
              <a href="{{ vacancy.get_absolute_url }}" class="btn btn-outline-primary">Ver mais..</a>
            </div>

            <div class="card-footer d-flex justify-content-between">
                <span>Candidaturas: {{vacancy.candidate_count}}</span>
                <a href="{% url 'business:candidacy-list' vacancy.vid %}" class="">Ver</a>
            </div>
          </div>
        </article>
      {% empty %}
        <p class="text-muted">Ainda não há ofertas de trabalho publicadas!</p>
      {% endfor %}

      
      
    </div>
  </div>
{% endblock %}

{% block local_script %}

{% endblock %}