apps/business/urls.py
""" Business urls for """
from django.urls import path
from . import views

app_name = "business"

urlpatterns = [
    path('vagas/', views.vacancy_list, name="vacancy-list"),
    path('vagas/nova-vaga/', views.register_vacancy, name="register-vacancy"),
    path('vagas/apagar-vaga/<uuid:vid>/', views.delete_vacancy, name="delete-vacancy"),
    path('vagas/adicionar-requisito/<uuid:vid>/', views.add_vacancy_skills, name="add-vacancy-skill"),
    path('vagas/adicionar-responsabilidade/<uuid:vid>/', views.add_vacancy_responsibilities, name="add-vacancy-responsibility"),
    path('vagas/adicionar-beneficio/<uuid:vid>/', views.add_vacancy_benefits, name="add-vacancy-benefits"),
    path('vagas/edit-vaga/<uuid:vid>/', views.edit_vacancy, name="edit-vacancy"),
    path('vagas/<slug:company_slug>/detalhes/<uuid:vid>/', views.vacancy_detail, name="vacancy-detail"),
    
    path('vagas/requisito/apagar/<uuid:sid>/', views.delete_skill, name="delete-skill"),
    path('vagas/beneficio/apagar/<uuid:bid>/', views.delete_benefit, name="delete-benefit"),
    path('vagas/responsabilidade/apagar/<uuid:rid>/', views.delete_responsibility, name="delete-responsibility"),
    
    path('perfil-do-usuario/<uuid:uid>/', views.user_profile, name="user-profile"),
    path('perfil-do-usuario/candidato/<uuid:uid>/', views.candidate_user_profile, name="candidate-user-profile"),
    path('candidaturas/<uuid:vid>/', views.candidacy_list, name="candidacy-list"),
    path('candidaturas/analise/<uuid:vid>/', views.candidacy_analyses, name="candidacy-analyses"),
]

setup/urls.py
""" Global url project """

from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pessoal/', include('apps.personal.urls')),
    path('empresarial/', include('apps.business.urls')),
    path('accounts/', include('apps.accounts.urls')),
    path('', include('apps.general.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/business/forms/vacancy_benefits_form.py
"""register form for vacancy skills"""

from django import forms
from ..models import Benefit


class VacancyBenefitForm(forms.ModelForm):
    """register vacancy benefit form model"""
    class Meta:
        model = Benefit
        fields = ['title']

    title = forms.CharField(
        label="Curta Descrição",
        required=True,
        max_length=255,
        widget=forms.TextInput(attrs={
            "placeholder":"Descrição",
            "class":"form-control",
            "tamanho":"col-12 mt-4",
        }),
        error_messages={
            "required":"O campo Descrição não pode estar vazio!" 
        },
    )

    def clean_title(self):
        """remove the whitespaces at the end of string"""
        return self.cleaned_data.get('title').strip()

apps/business/forms/vacancy_responsibilities_form.py
"""register form for vacancy skills"""

from django import forms
from ..models import Responsibility


class VacancyResponsibilityForm(forms.ModelForm):
    """register vacancy form model"""
    class Meta:
        model = Responsibility
        fields = ['title']

    title = forms.CharField(
        label="Curta Descrição",
        required=True,
        max_length=255,
        widget=forms.TextInput(attrs={
            "placeholder":"Descrição",
            "class":"form-control",
            "tamanho":"col-12 mt-4",
        }),
        error_messages={
            "required":"O campo Descrição não pode estar vazio!" 
        },
    )

    def clean_title(self):
        """remove the whitespaces at the end of string"""
        return self.cleaned_data.get('title').strip()

apps/business/forms/vacancy_skills_form.py
"""register form for vacancy skills"""

from django import forms
from ..models import Skill


class VacancySkillForm(forms.ModelForm):
    """register vacancy form model"""
    class Meta:
        model = Skill
        fields = ['title']

    title = forms.CharField(
        label="Curta Descrição",
        required=True,
        max_length=255,
        widget=forms.TextInput(attrs={
            "placeholder":"Descrição",
            "class":"form-control",
            "tamanho":"col-12 mt-4",
        }),
        error_messages={
            "required":"O campo Descrição não pode estar vazio!" 
        },
    )

    def clean_title(self):
        """remove the whitespaces at the end of string"""
        return self.cleaned_data.get('title').strip()

apps/business/views.py
""" Business Views"""
from django.db.models import Count
from django.views import View
from django.urls import reverse
from django.views import generic
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.contrib.auth import get_user_model

from apps.personal.models import Formation, ProfissionalExperience, Documentation
from apps.personal.models import AcademicFormationItem, ProfissionalFormationItem
from apps.personal.models import ProfissionalExperienceItem

from apps.business.models import Skill, Responsibility, Benefit
from .models import Vacancy, Candidate
from .forms import RegisterVacancyForm, VacancySkillForm
from .forms import VacancyResponsibilityForm, VacancyBenefitForm
from . import charts
User = get_user_model()


class CandidateUserProfileView(View):
    template_name = "business/candidate-user-profile.html"
    def get(self, request, *args, **kwargs):
        owner = User.objects.get(uid=self.kwargs.get('uid'))
        formation, _ = Formation.objects.get_or_create(user=owner)
        experience, _ = ProfissionalExperience.objects.get_or_create(user=owner)
        documentation, _ = Documentation.objects.get_or_create(user=owner)

        acad_formation_items = AcademicFormationItem.objects.filter(formation=formation)
        prof_formation_items = ProfissionalFormationItem.objects.filter(formation=formation)
        prof_experience_items = ProfissionalExperienceItem.objects.filter(profissional_experience=experience)

        candidates = Candidate.objects.filter(user=owner)
        

        return render(self.request, self.template_name, {
            "acad_formation_items":acad_formation_items,
            "prof_formation_items":prof_formation_items,
            "prof_experience_items":prof_experience_items,
            "documentation": documentation,
            "candidates":candidates,
            "owner":owner,
        })
candidate_user_profile = CandidateUserProfileView.as_view()

def user_profile(request, uid):
    total_vacancies = Vacancy.objects.filter(company=request.user)
    total_vacancies_active = Vacancy.objects.filter(company=request.user, expiration_data__gt = timezone.now().date())
    total_users = User.objects.exclude(uid=request.user.uid)
    total_candidates = Candidate.objects.all()
    labels_bar_vacancies_by_month, data_bar_vacancies_by_month = charts.get_vacancies_by_month()
    labels_users_by_month_line, data_users_by_month_line = charts.get_users_by_month()
    labels_users_gender_pie, data_users_gender_pie = charts.get_users_gender_pie()
    labels_users_without_pie, data_users_without_pie = charts.get_users_without_cv_pie()

    print(labels_users_by_month_line)
    print(data_users_by_month_line)

    return render(request, "business/user-profile.html", {
        'total_vacancies': total_vacancies,
        'total_vacancies_active': total_vacancies_active,
        'total_users': total_users,
        'total_candidates': total_candidates,
        'labels_bar_vacancies_by_month':labels_bar_vacancies_by_month,
        'data_bar_vacancies_by_month':data_bar_vacancies_by_month,
        'labels_users_by_month_line':labels_users_by_month_line,
        'data_users_by_month_line':data_users_by_month_line,
        'labels_users_gender_pie':labels_users_gender_pie,
        'data_users_gender_pie':data_users_gender_pie,
        'labels_users_without_pie':labels_users_without_pie,
        'data_users_without_pie':data_users_without_pie,
    })

@method_decorator(
    [login_required(login_url='landing_page', redirect_field_name="next")],name='dispatch')
class CandidacyAnalysesView(View):
    """analyses View """
    model = Candidate
    template_name = "business/candidacy_analyses.html"
    context_object_name = 'candidates'
    def get(self, request, *args, **kwargs):
        """get all  candidates applied to the vacancy"""
        vacancy = Vacancy.objects.get(vid=self.kwargs.get('vid'))
        candidates = Candidate.objects.filter(vacancy=vacancy)
        total_candidates = len(candidates)
        # paginator = Paginator(list_candidates,5)
        # candidates = paginator.get_page(self.request.GET.get('page'))

        return render(self.request, self.template_name,
                      {'candidates': candidates, "vacancy": vacancy,
                       "total_candidates":total_candidates})
candidacy_analyses = CandidacyAnalysesView.as_view()


@method_decorator(
    [login_required(login_url='landing_page', redirect_field_name="next")],name='dispatch')
class CandidacyListView(View):
    """List View for all candidate applied in a vacancy"""
    model = Candidate
    template_name = "business/candidacy_list.html"
    context_object_name = 'candidates'
    paginate_by = 5
    def get(self, request, *args, **kwargs):
        """get all  candidates applied to the vacancy"""
        vacancy = Vacancy.objects.get(vid=self.kwargs.get('vid'))
        list_candidates = Candidate.objects.filter(vacancy=vacancy)
        total_candidates = len(list_candidates)
        paginator = Paginator(list_candidates,5)
        candidates = paginator.get_page(self.request.GET.get('page'))

        return render(self.request, self.template_name, {'candidates': candidates, "vacancy": vacancy, "total_candidates":total_candidates})
candidacy_list = CandidacyListView.as_view()

class _BasicVacancyEditViewModel(View):
    template_name = "business/vacancy_edit.html"
    form_class = RegisterVacancyForm

    def get_instance(self) -> Vacancy:
        """get the current edit instance of vacancy 
        Returns:
            Vacancy: current vacancy
        """
        vacancy = Vacancy.objects.get(vid=self.kwargs.get("vid"))
        return vacancy

    def get(self, *args, **kwargs):
        """retrieve edit page with forms"""
        vacancy = self.get_instance()
        vacancy_information_form = self.form_class(self.request.session.get("vacancy_basic_form_data", None),instance=vacancy)
        vacancy_skills_form = VacancySkillForm(self.request.session.get("vacancy_skills_form_data", None))
        vacancy_responsibilities_form = VacancySkillForm(self.request.session.get("vacancy_responsibility_form_data", None))
        vacancy_benefits_form = VacancySkillForm(self.request.session.get("vacancy_benefits_form_data", None))
        return render(self.request, self.template_name, {
            "vacancy":vacancy, 
            "vacancy_information_form":vacancy_information_form,
            "vacancy_skills_form":vacancy_skills_form,
            "vacancy_responsibilities_form":vacancy_responsibilities_form,
            "vacancy_benefits_form":vacancy_benefits_form
        })

@method_decorator(
    [login_required(login_url='landing_page', redirect_field_name="next")],name='dispatch')
class VacancyBenefitsViewEdit(_BasicVacancyEditViewModel):
    """edit vacancy skills view"""
    form_class = VacancyBenefitForm

    def post(self,*args, **kwargs):
        """ save benefits"""
        self.request.session['vacancy_benefits_form_data'] = self.request.POST
        form = self.form_class(self.request.POST)
        if form.is_valid():
            benefit = form.save(commit=False)
            benefit.vacancy = self.get_instance()
            benefit.save()
            messages.success(self.request, "Benefício salvo com sucesso!")
            del self.request.session['vacancy_benefits_form_data']
        print(form.errors)
        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER') or '')
add_vacancy_benefits = VacancyBenefitsViewEdit.as_view()

@method_decorator(
    [login_required(login_url='landing_page', redirect_field_name="next")],name='dispatch')
class VacancyResponsibilityViewEdit(_BasicVacancyEditViewModel):
    """edit vacancy responsibility view"""
    form_class = VacancyResponsibilityForm

    def post(self,*args, **kwargs):
        """ save responsibility"""
        self.request.session['vacancy_responsibility_form_data'] = self.request.POST
        form = self.form_class(self.request.POST)
        if form.is_valid():
            responsibility = form.save(commit=False)
            responsibility.vacancy = self.get_instance()
            responsibility.save()
            messages.success(self.request, "Responsabilidade salva com sucesso!")
            del self.request.session['vacancy_responsibility_form_data']
        print(form.errors)
        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER') or '')
add_vacancy_responsibilities = VacancyResponsibilityViewEdit.as_view()

@method_decorator(
    [login_required(login_url='landing_page', redirect_field_name="next")],name='dispatch')
class VacancySkillSViewEdit(_BasicVacancyEditViewModel):
    """edit vacancy skills view"""
    form_class = VacancySkillForm

    def post(self,*args, **kwargs):
        """ save skills"""
        self.request.session['vacancy_skills_form_data'] = self.request.POST
        form = self.form_class(self.request.POST)
        if form.is_valid():
            skill = form.save(commit=False)
            skill.vacancy = self.get_instance()
            skill.save()
            messages.success(self.request, "Requisito salvo com sucesso!")
            del self.request.session['vacancy_skills_form_data']
        print(form.errors)
        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER') or '')
add_vacancy_skills = VacancySkillSViewEdit.as_view()

@method_decorator(
    [login_required(login_url='landing_page', redirect_field_name="next")],name='dispatch')
class DeleteResponsibilityView(View):
    """delete vacancy responsibility view"""
    def post(self, *args, **kwargs):
        """post method for delete processing request
        Returns:
            http redirect response: redirect url view
        """

templates/business/partials/_sidebar.html
{% load static %}
<nav class="sidebar sidebar-offcanvas" id="sidebar">
  <ul class="nav">

    <li class="nav-item">
      <div class="d-flex sidebar-profile">
        <div class="sidebar-profile-image">
          <img src="{{ request.user.company_profile.image_url}}" alt="{{request.user.get_full_name}}" />
          <span class="sidebar-status-indicator"></span>
        </div>
        <div class="sidebar-profile-name">
          <p class="sidebar-name">
            {{request.user.get_full_name}}
          </p>
          <p class="sidebar-designation">
            Bem Vindo
          </p>
        </div>
      </div>
      <p class="sidebar-menu-title">Menu</p>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'business:user-profile' request.user.uid %}">
        <i class="typcn typcn-device-desktop menu-icon"></i>
        <span class="menu-title">Início</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'business:vacancy-list'  %}">
        <i class="typcn typcn-device-desktop menu-icon"></i>
        <span class="menu-title">Meus Anúncios de Vaga</span>
      </a>
    </li>
    
    <li class="nav-item">
      <a class="nav-link" href="/admin">
        <i class="typcn typcn-device-desktop menu-icon"></i>
        <span class="menu-title"> Outras opções</span>
      </a>
    </li>
    
  </ul>
</nav>

templates/business/partials/_vacancy_benefits_tab.html
{% load static %}
<section class="tab-pane fade" id="pills-benefits" role="tabpanel" aria-labelledby="pills-benefits-tab">
  <div class="row justify-content-center">
    <div class="col-12">
      <h2>Benefícios do Cargo</h2>
      <p class="card-description">Coloque o que a pessoa terá de fazer quando for contratada</p>

      <form method="post" action="{% url 'business:add-vacancy-benefits' vacancy.vid %}" class="forms-sample">
        {% csrf_token %}

        <div class="row justify-content-end text-start">
          {% for field in vacancy_benefits_form.visible_fields %}
            <div class="col-12">
              <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {{ field }}

              {% if field.help_text %}
                <p class="text-muted">
                  <small>{{ field.help_text }}</small>
                </p>
              {% endif %}

              {% if field.errors %}
                <div class="text-danger error-messages">{{ field.errors }}</div>
              {% endif %}
            </div>
          {% endfor %}

          <div class="col-6">
            <label for="" class="w-100" style="visibility: hidden;">Adicionar</label>
            <button type="submit" class="btn btn-primary w-100" id="btnAddItens">
              <i class="bi bi-plus-circle-fill"></i>
              Adicionar
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
</section>

templates/business/partials/_vacancy_delete_modal.html
{% load static %}
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Eliminar Anúncio da vaga {{ vacancy.title }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">Tem a certeza de que deseja eliminar o anúncio?</div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <form method="post" action="{% url 'business:delete-vacancy' vacancy.vid %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-info">
            <i class="bi bi-trash"></i>
            Sim
          </button>
        </form>
      </div>
    </div>
  </div>
</div>

templates/business/partials/_vacancy_edit_preview.html
{% load static %}

<div class="card">
  <div class="card-body">
    <h2 class="card-title">Vaga: {{ vacancy.title }}</h2>
    <p class="text-muted h5">
      <i class="bi bi-clock-fill"></i> Data de registro: <span class="text-success">{{ vacancy.created_at }}</span>
    </p>

    <p class="card-title" style="font-size:medium;">
      <span>
        <i class="bi bi-geo-alt-fill"></i>
        <span class="badge badge-warning">{{ vacancy.city }}</span>
      </span>

      <span class="mx-3">
        <i class="bi bi-briefcase-fill"></i>
        <span class="badge badge-success">{{ vacancy.job_type }}</span>
      </span>
    </p>

    <div>
      <p>{{ vacancy.description|safe }}</p>
    </div>

    {% if vacancy.get_skills %}
      <div class="mt-5">
        <h2 class="h4">Requisitos Técnicos</h2>
        <ul class="ml-4">
          {% for skill in vacancy.get_skills %}
            <li>{{ skill.title }}</li>
          {% empty %}
            <p class="text-muted">Não há requisitos especificados para esta vaga</p>
          {% endfor %}
        </ul>
      </div>
    {% endif %}

    {% if vacancy.get_responsibilities %}
      <div class="mt-5">
        <h2 class="h4">Responsabilidades</h2>
        <ul class="ml-4">
          {% for responsibility in vacancy.get_responsibilities %}
            <li>{{ responsibility.title }}</li>
          {% empty %}
            <p class="text-muted">Não há responsabilidades especificadas para esta vaga</p>
          {% endfor %}
        </ul>
      </div>
    {% endif %}

    {% if vacancy.get_benefits %}
      <div class="mt-5">
        <h2 class="h4">Benefícios</h2>
        <ul class="ml-4">
          {% for responsibility in vacancy.get_benefits %}
            <li>{{ responsibility.title }}</li>
          {% empty %}
            <p class="text-muted">Não há responsabilidades especificadas para esta vaga</p>
          {% endfor %}
        </ul>
      </div>
    {% endif %}
  </div>
</div>

templates/business/partials/_vacancy_information_tab.html
{% load static %}

<section class="tab-pane fade" id="pills-basic-informations" role="tabpanel" aria-labelledby="pills-basic-informations-tab">
    <div class="row">
      <div class="col-12">
          <h2>Informações Básicas da Vaga</h2>
          <p class="card-description">Mantenha os dados de contacto sempre actualizados!</p>
          <form action="{% url 'business:edit-vacancy' vacancy.vid %}" method="post" class="forms-sample" enctype="multipart/form-data">
              {% csrf_token %}
              {% for field in vacancy_information_form.visible_fields %}
              <div class="form-group">
                  <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                  {{ field }}
                  
                  {% if field.help_text %}
                  <p class="text-muted">
                      <small>{{ field.help_text }}</small>
                    </p>
                    {% endif %}
                    
                    {% if field.errors %}
                    <div class="text-danger error-messages">{{ field.errors }}</div>
                    {% endif %}
                    
                    {% if field.name == 'image' and field.value %}
                    <div class="w-50 mx-auto">
                        <img class="w-100" src="{{ field.value.url }}" alt="Capa de {{vacancy.title}}" />
                    </div>
                    {% endif %}
                </div>
                {% endfor %}
                
                <button type="submit" class="btn btn-primary mr-2 rounded">
                    <i class="bi bi-pencil-square"></i>
                Salvar
            </button>
            </form>
        </div>
    </div>
</section>

templates/business/partials/_vacancy_requirements_tab.html
{% load static %}
<section class="tab-pane fade show active" id="pills-skills" role="tabpanel" aria-labelledby="pills-skills-tab">
  <div class="row justify-content-center">
    <div class="col-12">
      <h2>Habilidades requeridas para os candidatos</h2>
      <p class="card-description">Coloque as habilidades mais essenciais para uma melhor seleção</p>

      <form method="post" action="{% url 'business:add-vacancy-skill' vacancy.vid %}" class="forms-sample">
        {% csrf_token %}

        <div class="row justify-content-end text-start">
          {% for field in vacancy_skills_form.visible_fields %}
            <div class="col-12">
              <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {{ field }}

              {% if field.help_text %}
                <p class="text-muted">
                  <small>{{ field.help_text }}</small>
                </p>
              {% endif %}

              {% if field.errors %}
                <div class="text-danger error-messages">{{ field.errors }}</div>
              {% endif %}
            </div>
          {% endfor %}

          <div class="col-6">
            <label for="" class="w-100" style="visibility: hidden;">Adicionar</label>
            <button type="submit" class="btn btn-primary w-100" id="btnAddItens">
              <i class="bi bi-plus-circle-fill"></i>
              Adicionar
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
</section>

templates/business/partials/_vacancy_responsabilities_tab.html
{% load static %}
<section class="tab-pane fade" id="pills-responsibilities" role="tabpanel" aria-labelledby="pills-responsibilities-tab">
  <div class="row justify-content-center">
    <div class="col-12">
      <h2>Resposabilidades do Cargo</h2>
      <p class="card-description">Coloque o que a pessoa terá de fazer quando for contratada</p>

      <form method="post" action="{% url 'business:add-vacancy-responsibility' vacancy.vid %}" class="forms-sample">
        {% csrf_token %}

        <div class="row justify-content-end text-start">
          {% for field in vacancy_responsibilities_form.visible_fields %}
            <div class="col-12">
              <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {{ field }}

              {% if field.help_text %}
                <p class="text-muted">
                  <small>{{ field.help_text }}</small>
                </p>
              {% endif %}

              {% if field.errors %}
                <div class="text-danger error-messages">{{ field.errors }}</div>
              {% endif %}
            </div>
          {% endfor %}

          <div class="col-6">
            <label for="" class="w-100" style="visibility: hidden;">Adicionar</label>
            <button type="submit" class="btn btn-primary w-100" id="btnAddItens">
              <i class="bi bi-plus-circle-fill"></i>
              Adicionar
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
</section>