apps/personal/urls.py
""" urls from personal """
from django.urls import path
from . import views

app_name= "personal"

urlpatterns = [
    path('perfil/atualizar/', views.profile_update, name="profile-update"),
    path('formacao/academica/nova/', views.add_academic_formation, name="add-academic-formation"),
    path('formacao/academica/eliminar/<uuid:id>', views.delete_academic_formation, name="delete-academic-formation"),
    path('formacao/profissional/nova/', views.add_profissional_formation, name="add-profissional-formation"),
    path('formacao/profissional/eliminar/<uuid:id>', views.delete_profissional_formation, name="delete-profissional-formation"),
    
    path('experiencia-profissional/nova/', views.add_profissional_experience, name="add-profissional-experience"),
    path('documentacao/atualizar/', views.add_documentation, name="add-documentation"),
    

    path('minha-carreira-profissional/', views.career, name="career"),

    path('vagas/', views.vacancy_list, name="vacancy-list"),
    path('vagas/<slug:company_slug>/detalhes/<uuid:vid>/', views.vacancy_detail, name="vacancy-detail"),
    path('candidaturas/adicionar-candidatura/<uuid:vid>/', views.apply_for_vacancy, name="apply-for-vacancy"),

    path('minhas-candidaturas/', views.my_candidates, name="my-candidates"),
    
    path('perfil-do-usuario/<uuid:uid>', views.user_profile, name="user-profile"),
]

setup/urls.py
""" Global url project """

from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pessoal/', include('apps.personal.urls')),
    path('empresarial/', include('apps.business.urls')),
    path('accounts/', include('apps.accounts.urls')),
    path('', include('apps.general.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/personal/forms/personal_documentation_form.py
from django import forms
from ..models import Documentation
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError

# from django.contrib.auth.models import User
User = get_user_model()

class PersonalDocumentationForm(forms.ModelForm):
    class Meta:
        model = Documentation
        fields = [
            "bi", 
            "cv", 
            "certificate_literary", 
            "medical_certificate", 
            "other_doc1", 
            "other_doc2", 
            "other_doc3", 
            "other_doc4", 
            "other_doc5", 
            "other_doc6", 
            "other_doc7", 
            "other_doc8", 
            "other_doc9", 
            "other_doc10", 
        ]

    bi = forms.FileField(
        label='Bilhete de Identidade',
        required=True,
        widget=forms.FileInput(attrs={"class":"file-upload-default", "accept":"image/*,application/pdf"}),
        help_text="*" 
    )
    
    cv = forms.FileField(
        label='Curriculum Vitae',
        required=True,
        widget=forms.FileInput(attrs={"class":"file-upload-default", "accept":"image/*,application/pdf"}), 
        help_text="*" 
    )
    
    certificate_literary = forms.FileField(
        label='Certificado de Habilitações Literais',
        required=True,
        widget=forms.FileInput(attrs={"class":"file-upload-default", "accept":"image/*,application/pdf"}), 
        help_text="*" 
    )
    
    medical_certificate = forms.FileField(
        label='Atestado Médico',
        required=False,
        widget=forms.FileInput(attrs={"class":"file-upload-default", "accept":"image/*,application/pdf"}), 
    )
    
    other_doc1 = forms.FileField(
        label='Outro Documentos 1',
        required=False,
        widget=forms.FileInput(attrs={"class":"file-upload-default", "accept":"image/*,application/pdf"}), 
    )
    other_doc2 = forms.FileField(
        label='Outro Documentos 2',
        required=False,
        widget=forms.FileInput(attrs={"class":"file-upload-default", "accept":"image/*,application/pdf"}), 
    )
    other_doc3 = forms.FileField(
        label='Outro Documentos 3',
        required=False,
        widget=forms.FileInput(attrs={"class":"file-upload-default", "accept":"image/*,application/pdf"}), 
    )
    other_doc4 = forms.FileField(
        label='Outro Documentos 4',
        required=False,
        widget=forms.FileInput(attrs={"class":"file-upload-default", "accept":"image/*,application/pdf"}), 
    )
    other_doc5 = forms.FileField(
        label='Outro Documentos 5',
        required=False,
        widget=forms.FileInput(attrs={"class":"file-upload-default", "accept":"image/*,application/pdf"}), 
    )
    other_doc6 = forms.FileField(
        label='Outro Documentos 6',
        required=False,
        widget=forms.FileInput(attrs={"class":"file-upload-default", "accept":"image/*,application/pdf"}), 
    )

    other_doc7 = forms.FileField(
        label='Outro Documentos 7',
        required=False,
        widget=forms.FileInput(attrs={"class":"file-upload-default", "accept":"image/*,application/pdf"}), 
    )
    
    other_doc8 = forms.FileField(
        label='Outro Documentos 8',
        required=False,
        widget=forms.FileInput(attrs={"class":"file-upload-default", "accept":"image/*,application/pdf"}), 
    )

    other_doc9 = forms.FileField(
        label='Outro Documentos 9',
        required=False,
        widget=forms.FileInput(attrs={"class":"file-upload-default", "accept":"image/*,application/pdf"}), 
    )

    other_doc10 = forms.FileField(
        label='Outro Documentos 10',
        required=False,
        widget=forms.FileInput(attrs={"class":"file-upload-default", "accept":"image/*,application/pdf"}), 
    )

    

apps/personal/forms/personal_experience_form.py
from django import forms
from django.contrib.auth import get_user_model
from ..models import ProfissionalExperienceItem

User = get_user_model()

class ProfissionalExperienceForm(forms.ModelForm):
    class Meta:
        model = ProfissionalExperienceItem
        fields = ["institution", "years", "description",]
        
    institution = forms.CharField(
        label="Instituição",
        required=True,
        max_length=255,
        widget=forms.TextInput(attrs={
            "placeholder":"Instituição onde trabalhou", 
            "class":"form-control",
        }), 
    )

    years = forms.IntegerField(
        label="Quantos anos de trabalho",
        required=True,
        widget=forms.NumberInput(attrs={
            "placeholder":"Quantos anos de trabalho você teve na empresa?", 
            "class":"form-control",
            "min":0,
            "max":80,
        }), 
    )
    
    description = forms.CharField(
        label="Descrição",
        required=True,
        widget=forms.Textarea(attrs={
            "placeholder":"Fale sobre o trabalho que realizou, a experiência que obteve", 
            "class":"form-control",
        }), 
    )

    
    def clean_institution(self):
        institution = self.cleaned_data.get('institution').strip()
        return institution
    
    def clean_description(self):
        description = self.cleaned_data.get('description').strip()
        return description
    

apps/personal/views.py
from typing import Any
from django.urls import reverse
from django.shortcuts import render
from django.contrib import messages
from django.views import View, generic
from django.http import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model

from apps.accounts.models import PersonalProfile
from apps.business.models import Vacancy, Candidate
from .forms import PersonalInformationForm, PersonalProfileInformationForm, AcademicFormationForm
from .forms import ProfissionalFormationForm, ProfissionalExperienceForm, PersonalDocumentationForm
from .models import Formation, AcademicFormationItem, ProfissionalFormationItem
from .models import ProfissionalExperienceItem, ProfissionalExperience, Documentation

User = get_user_model()

class UserProfileView(View):
    template_name = "personal/user-profile.html"
    def get(self, request, *args, **kwargs):
        owner = User.objects.get(uid=self.kwargs.get('uid'))
        formation, _ = Formation.objects.get_or_create(user=owner)
        experience, _ = ProfissionalExperience.objects.get_or_create(user=owner)
        documentation, _ = Documentation.objects.get_or_create(user=owner)

        acad_formation_items = AcademicFormationItem.objects.filter(formation=formation)
        prof_formation_items = ProfissionalFormationItem.objects.filter(formation=formation)
        prof_experience_items = ProfissionalExperienceItem.objects.filter(profissional_experience=experience)

        candidates = Candidate.objects.filter(user=owner)
        

        return render(self.request, self.template_name, {
            "acad_formation_items":acad_formation_items,
            "prof_formation_items":prof_formation_items,
            "prof_experience_items":prof_experience_items,
            "documentation": documentation,
            "candidates":candidates,
            "owner":owner,
        })
user_profile = UserProfileView.as_view()

@method_decorator(
    [login_required(login_url='landing_page', redirect_field_name="next"),], name='dispatch')
class MyCandidateListView(View):
    """my candidate list view"""

    template_name = "personal/my-candidates.html"
    def get(self, request, *args, **kwargs):
        """get template list of vacancies applied"""
        candidates = Candidate.objects.filter(user=self.request.user)
        return render(self.request, self.template_name, {"candidates":candidates})
my_candidates = MyCandidateListView.as_view()


@method_decorator(
    [login_required(login_url='landing_page', redirect_field_name="next"),], name='dispatch')
class RegisterCandidacy(View):
    """ Register Candidacy View"""

    def post(self, request, *args, **kwargs):
        """ registers a candidate"""
        vacancy = Vacancy.objects.get(vid=self.kwargs.get('vid'))
        candidate = Candidate.objects.filter(user=self.request.user, vacancy=vacancy)

        if candidate.exists():
            messages.error(self.request, "Você já se candidatou a está vaga")
            return HttpResponseRedirect(self.request.META.get('HTTP_REFERER') or '')

        if self.request.user.type != "P":
            messages.error(self.request, "Só contas particulares podem se candidatar a vagas")
            return HttpResponseRedirect(self.request.META.get('HTTP_REFERER') or '')

        documentations = Documentation.objects.filter(user=self.request.user)
        if not documentations.exists():
            messages.error(self.request, "A sua conta não possui nenhuma documentação associada ao perfil. Conclua primeiro o seu perfil!")
            return HttpResponseRedirect(self.request.META.get('HTTP_REFERER') or '')

        documentation = documentations.first()
        if not documentation.cv:
            messages.error(self.request, "A sua conta não possui um CV registado no perfil! Adicione o seu cv primeiro")
            return HttpResponseRedirect(self.request.META.get('HTTP_REFERER') or '')

        Candidate.objects.create(user=self.request.user, vacancy=vacancy, cv=documentation.cv)
        messages.success(self.request,"Sua candidatura foi enviada com sucesso!")
        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER') or '')
apply_for_vacancy = RegisterCandidacy.as_view()


@method_decorator(
    [login_required(login_url='landing_page', redirect_field_name="next")],name='dispatch')
class VacancyDetailView(generic.DetailView):
    """Detail View for a specific vacancy"""
    model = Vacancy
    template_name = "personal/vacancy_detail.html"
    context_object_name = "vacancy"

    def get_object(self, *args, **kwargs):
        return Vacancy.objects.get(vid=self.kwargs.get('vid'))

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        ctx = super().get_context_data(**kwargs)
        ctx['applied'] = Candidate.objects.filter(
            user=self.request.user,
            vacancy = Vacancy.objects.get(vid=self.kwargs.get('vid'))
        ).exists()
        print(ctx)
        return ctx
vacancy_detail = VacancyDetailView.as_view()

@method_decorator([login_required(login_url='landing_page', redirect_field_name="next"),], name='dispatch')
class VacancyListView(View):
    """render a list of vacancies for participants applying"""
    template_name = "personal/vacancy_list.html"
    def get(self, *args, **kwargs):
        """get template list of vacancies"""
        vacancies = Vacancy.objects.all()
        return render(self.request, self.template_name, {"vacancies":vacancies})
vacancy_list= VacancyListView.as_view()

@method_decorator([login_required(login_url='landing_page', redirect_field_name="next"),], name='dispatch')
class CareerView(View):
    template_name = "personal/career.html"
    def get(self, request, *args, **kwargs):
        formation, _ = Formation.objects.get_or_create(user=request.user)
        experience, _ = ProfissionalExperience.objects.get_or_create(user=request.user)
        documentation , _ = Documentation.objects.get_or_create(user=request.user)

        personal_info_form = PersonalInformationForm(instance=request.user)
        personal_profile_form = PersonalProfileInformationForm(request.session.get('personal_info_form_data'), instance=request.user.personal_profile)
        
        personal_academic_formation_form = AcademicFormationForm(request.session.get('personal_academic_formation_form_data', None))
        personal_profissional_formation_form = ProfissionalFormationForm(request.session.get('personal_profissional_formation_form_data', None))

        personal_profissional_experience_form = ProfissionalExperienceForm(request.session.get('personal_profissional_experience_form_data', None))
        personal_documentation_form = PersonalDocumentationForm(request.session.get('doc_files_form_data', None), instance=documentation)


        acad_formation_items = AcademicFormationItem.objects.filter(formation=formation)
        prof_formation_items = ProfissionalFormationItem.objects.filter(formation=formation)

        prof_experience_items = ProfissionalExperienceItem.objects.filter(profissional_experience=experience)

        

        return render(self.request, self.template_name, {
            "personal_info_form":personal_info_form,
            "personal_profile_form":personal_profile_form,
            "personal_academic_formation_form":personal_academic_formation_form,
            "personal_profissional_formation_form":personal_profissional_formation_form,

            "personal_profissional_experience_form":personal_profissional_experience_form,
            "personal_documentation_form":personal_documentation_form,

            "acad_formation_items":acad_formation_items,
            "prof_formation_items":prof_formation_items,          
            "prof_experience_items":prof_experience_items,

            })
career = CareerView.as_view()

@method_decorator([login_required(login_url='landing_page', redirect_field_name="next"),], name='dispatch')
class AddDocumentation(View):
    form_class = PersonalDocumentationForm
    def post(self, request, *args, **kwargs):
        documentation , _ = Documentation.objects.get_or_create(user=request.user)
        request.session['personal_documentation_form_data'] = request.POST
        request.session['doc_files_form_data'] = request.FILES
        form = self.form_class(request.session['personal_documentation_form_data'], request.FILES, instance=documentation)
        if form.is_valid():
            doc = form.save(commit=False)
            doc.user = request.user
            doc.save()
            messages.success(request, "Documentos Carregados com sucesso!")
            del(request.session['personal_documentation_form_data'])
            del(request.session['doc_files_form_data'])
        else:
            messages.error(request, "Erro: Carregue todos os documentos obrigatórios!")
            print(form.errors)
        previous_page = self.request.META.get('HTTP_REFERER')
        return HttpResponseRedirect(previous_page or '')
add_documentation = AddDocumentation.as_view()

@method_decorator([login_required(login_url='landing_page', redirect_field_name="next"),], name='dispatch')
class AddProfissionalExperienceItem(View):
    form_class = ProfissionalExperienceForm

    def post(self, request, *args, **kwargs):
        experience, created = ProfissionalExperience.objects.get_or_create(user=request.user)
        request.session['personal_profissional_experience_form_data'] = request.POST
        form = self.form_class(request.session['personal_profissional_experience_form_data'])
        if form.is_valid():
            experience_item = form.save(commit=False)
            experience_item.profissional_experience = experience
            experience_item.save()
            messages.success(request, "Experiência Profissional Adicionada com sucesso!")
            del(request.session['personal_profissional_experience_form_data'])
        else:

templates/personal/partials/_experience.html
{% load static %}
<div class="tab-pane fade" id="pills-experience" role="tabpanel" aria-labelledby="pills-experience-tab">
    <h1 class="text-center"> Ter experiência na área a que está se candidatando pode </h1>


    <div class="row justify-content-center">
        <div class="col-10 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h2>Experiência Profissional</h2>
                    <p class="card-description">
                        Quanto mais experiência melhor as chances de ser recrutado!
                    </p>

                    <form method="post" action="{% url 'personal:add-profissional-experience' %}" class="forms-sample">
                        {% csrf_token %}

                        <div class="row justify-content-end text-start">
                            {% for field in personal_profissional_experience_form.visible_fields %}
                            <div class="col-12 mt-3">
                                <label for="{{ field.id_for_label }}"> {{ field.label }}</label>
                                {{ field }}

                                {% if field.help_text %}
                                <p class="text-muted"> <small>{{ field.help_text }}</small> </p>
                                {% endif %}

                                {% if field.errors %}
                                <div class="text-danger error-messages"> {{ field.errors }} </div>
                                {% endif %}
                            </div>
                            {% endfor %}

                            <div class="col-12">
                                <label for="" class="w-50" style="visibility: hidden;">Adicionar</label>
                                <button type="submit" class="btn btn-primary w-50 " id="btnAddItens">
                                    <i class="bi bi-pencil-square"></i>
                                    Adicionar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>


        {% for experience in  prof_experience_items %}
        <article class="col-10 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{{experience.institution}}</h4>
                    <p class="card-description">
                        {{experience.years}} anos de trabalho
                    </p>
                    <p>
                        {{experience.description}}
                    </p>
                </div>
            </div>
        </article>
        {% empty %}
        <p class="text-muted">Não há Experiências registradas</p>
        {% endfor %}
    </div>

</div>

templates/personal/partials/_formation.html
{% load static %}
<div class="tab-pane fade" id="pills-formation" role="tabpanel" aria-labelledby="pills-formation-tab">
    <h1 class="text-center">Sua Formação ajuda-nos a Saber o que você é capaz</h1>
    <div class="row justify-content-center">
        <div class="col-10 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h2>Formação Acadêmica</h2>
                    <p class="card-description">
                        Os seus dados ajudaram os recrutadores a saber mais sobre você!
                    </p>

                    <form method="post" action="{% url 'personal:add-academic-formation'%}" class="forms-sample">
                        {% csrf_token %}

                        <div class="row justify-content-end text-start">
                            {% for field in personal_academic_formation_form.visible_fields %}
                            <div class="col-12 col-sm-6 col-md-6 col-lg-4">
                                <label for="{{ field.id_for_label }}"> {{ field.label }}</label>
                                {{ field }}

                                {% if field.help_text %}
                                <p class="text-muted"> <small>{{ field.help_text }}</small> </p>
                                {% endif %}

                                {% if field.errors %}
                                <div class="text-danger error-messages"> {{ field.errors }} </div>
                                {% endif %}
                            </div>
                            {% endfor %}


                            <div class="col-12 col-sm-6 col-md-6 col-lg-4">
                                <label for="" class="w-100" style="visibility: hidden;">Adicionar</label>
                                <button type="submit" class="btn btn-primary w-100 " id="btnAddItens">
                                    <i class="bi bi-plus"></i>
                                    Adicionar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-10 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Formações Académicas</h4>
                    <p class="card-description">
                        Formações já registradas</code>
                    </p>
                    <div class="table-responsive">
                        <table class="table text-left">
                            <thead >
                                <tr>
                                    <th>Curso</th>
                                    <th>Instituição</th>
                                    <th>Ano de Início</th>
                                    <th>Ano de Termino</th>
                                    <th>Terminado</th>
                                    <th>Acções</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for formation in acad_formation_items %}
                                <tr>
                                    <td>{{formation.course}}</td>
                                    <td>{{formation.institution}}</td>
                                    <td>{{formation.start_year}}</td>
                                    <td>{{formation.end_year}}</td>
                                    <td>{{formation.get_finished_status}}</td>
                                    <td>
                                        <div class="d-flex align-items-center">
                                            <form method="post" action="{% url 'personal:delete-academic-formation' formation.aid %}">
                                                {% csrf_token %}
                                                <button title="Eliminar formação" type="submit"
                                                class="btn btn-primary btn-sm  mr-3" data-toggle="modal"
                                                data-target="#modalLawyerDelete{{lawyer.id}}">
                                                <i class="typcn typcn-delete-outline btn-icon-append"></i>
                                                Deletar
                                            </button>
                                        </form>
                                        </div>
                                    </td>
                                </tr>
                                {% empty %}
                                <tr>
                                    <td colspan="4"><p>Não há formações academicas registradas!</p></td>
                                </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-10 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h2>Formação Profissional</h2>
                    <p class="card-description">
                        Os seus dados ajudaram os recrutadores a saber mais sobre você!
                    </p>

                    <form method="post" action="{% url 'personal:add-profissional-formation' %}" class="forms-sample">
                        {% csrf_token %}
                        <div class="row justify-content-start text-start">
                            {% for field in personal_profissional_formation_form.visible_fields %}
                            <div class="col-12 col-sm-6 col-md-6 col-lg-4">
                                <label for="{{ field.id_for_label }}"> {{ field.label }}</label>
                                {{ field }}

                                {% if field.help_text %}
                                <p class="text-muted"> <small>{{ field.help_text }}</small> </p>
                                {% endif %}

                                {% if field.errors %}
                                <div class="text-danger error-messages"> {{ field.errors }} </div>
                                {% endif %}
                            </div>
                            {% endfor %}


                            <div class="col-12 col-sm-6 col-md-6 col-lg-4">
                                <label for="" class="w-100" style="visibility: hidden;">Adicionar</label>
                                <button type="submit" class="btn btn-primary w-100 " id="btnAddItens">
                                    <i class="bi bi-plus"></i>
                                    Adicionar
                                </button>
                            </div>
                        </div>

                    </form>

                </div>
            </div>
        </div>

        <div class="col-10 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Formações Profissionais</h4>
                    <p class="card-description">
                        Suas formações profissionais já registradas</code>
                    </p>
                    <div class="table-responsive">
                        <table class="table text-left">
                            <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th>Instituição</th>
                                    <th>Horas</th>
                                    <th>Ano</th>
                                    <th>Acções</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for formation in prof_formation_items %}
                                <tr>
                                    <td>{{formation.title}}</td>
                                    <td>{{formation.institution}}</td>
                                    <td>{{formation.hours}}</td>
                                    <td>{{formation.year}}</td>
                                    <td>
                                        <div class="d-flex align-items-center">
                                            <form method="post" action="{% url 'personal:delete-profissional-formation' formation.pid %}">
                                                {% csrf_token %}
                                                <button title="Eliminar formação rofissional" type="submit"
                                                class="btn btn-primary btn-sm  mr-3" data-toggle="modal"
                                                data-target="#modalLawyerDelete{{lawyer.id}}">
                                                <i class="typcn typcn-delete-outline btn-icon-append"></i>
                                                Deletar
                                            </button>
                                        </form>
                                        </div>
                                    </td>
                                </tr>
                                {% empty %}
                                <tr>
                                    <td colspan="4"><p>Não há formações academicas registradas!</p></td>
                                </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

templates/personal/partials/_sidebar.html
{% load static %}
<nav class="sidebar sidebar-offcanvas" id="sidebar">
  <ul class="nav">
    <li class="nav-item">
      <div class="d-flex sidebar-profile">
        <div class="sidebar-profile-image">
          <img src="{{ request.user.personal_profile.image_url }}" alt="{{ request.user.get_full_name }}" />
          <span class="sidebar-status-indicator"></span>
        </div>
        <div class="sidebar-profile-name">
          <p class="sidebar-name">{{ request.user.get_full_name }}</p>
          <p class="sidebar-designation">Bem Vindo</p>
        </div>
      </div>

      <p class="sidebar-menu-title">Menu</p>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'personal:user-profile' request.user.uid %}">
        <i class="bi bi-pc-display-horizontal menu-icon"></i>
        <span class="menu-title">Início</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'personal:career' %}">
        <i class="bi bi-person-bounding-box menu-icon"></i>
        <span class="menu-title">Minha Carreira</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'personal:vacancy-list' %}">
          <i class="bi bi-card-list menu-icon"></i>
          <span class="menu-title">Vagas</span>
        </a>
    </li>
    
    <li class="nav-item">
        <a class="nav-link" href="{% url 'personal:my-candidates' %}">
          <i class="bi bi-person-check menu-icon"></i>
        <span class="menu-title">Minhas Candidaturas</span>
      </a>
    </li>
  </ul>
</nav>